#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(WILL_O_WISP) \
    F(SWORDS_DANCE) \
    F(TRICK_ROOM) \
    F(SLEEP_TALK) \
    F(DRAGON_DANCE) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(FIRE_FANG) \
    F(PSYCHIC_FANGS) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(ICE_PUNCH) \
    F(FIRE_PUNCH) \
    F(THUNDER_PUNCH) \
    F(DRAIN_PUNCH) \
    F(PLAY_ROUGH) \
    F(U_TURN) \
    F(POISON_JAB) \
    F(INCINERATE) \
    F(SCALD) \
    F(VOLT_SWITCH) \
    F(DAZZLING_GLEAM) \
    F(HEX) \
    F(GRASS_KNOT) \
    F(SHADOW_CLAW) \
    F(STONE_EDGE) \
    F(AVALANCHE) \
    F(ZEN_HEADBUTT) \
    F(MOONBLAST) \
    F(BRUTAL_SWING) \
    F(LIQUIDATION) \
    F(DRACO_METEOR) \
    F(METEOR_MASH) \
    F(STEEL_BEAM) \
    F(CHILLING_WATER) \
    F(TRAILBLAZE) \
    F(SYNTHESIS) \
    F(HYPER_VOICE) \
    F(SACRED_SWORD) \
    F(FUSION_BOLT) \
    F(FUSION_FLARE) \
    F(BLUE_FLARE) \
    F(BOLT_STRIKE) \
    F(BRAVE_BIRD) \
    F(STEALTH_ROCK) \
    F(CRUNCH) \
    F(HYDRO_PUMP) \
    F(HI_JUMP_KICK) \
    F(FLAME_CHARGE) \
    F(BULLDOZE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
