poryOldaleTown_Mart_TM_Seller::
    lock
    faceplayer
    message OldaleTown_Text_TMsForSale
    waitmessage
    pokemart OldaleTown_Mart_TMs
    msgbox OldaleTown_Text_ComeAgain, MSGBOX_DEFAULT
    release
    end

.align 2
OldaleTown_Mart_TMs::
    .2byte ITEM_TM01     // TM01
    .2byte ITEM_TM02     // TM02
    .2byte ITEM_TM03     // TM03
    .2byte ITEM_TM04     // TM04
    .2byte ITEM_TM05     // TM05
    .2byte ITEM_TM06     // TM06
    .2byte ITEM_TM07     // TM07
    .2byte ITEM_TM08     // TM08
    .2byte ITEM_TM09     // TM09
    .2byte ITEM_TM10     // TM10
    .2byte ITEM_TM11     // TM11
    .2byte ITEM_TM12     // TM12
    .2byte ITEM_TM13     // TM13
    .2byte ITEM_TM14     // TM14
    .2byte ITEM_TM15     // TM15
    .2byte ITEM_TM16     // TM16
    .2byte ITEM_TM17     // TM17
    .2byte ITEM_TM18     // TM18
    .2byte ITEM_TM19     // TM19
    .2byte ITEM_TM20     // TM20
    .2byte ITEM_TM21     // TM21
    .2byte ITEM_TM22     // TM22
    .2byte ITEM_TM23     // TM23
    .2byte ITEM_TM24     // TM24
    .2byte ITEM_TM25     // TM25
    .2byte ITEM_TM26     // TM26
    .2byte ITEM_TM27     // TM27
    .2byte ITEM_TM28     // TM28
    .2byte ITEM_TM29     // TM29
    .2byte ITEM_TM30     // TM30
    .2byte ITEM_NONE
    end
