poryPetalburgCity_Mart_TM_Seller::
    lock
    faceplayer
    message PetalburgCity_Text_TMsForSale
    waitmessage
    pokemart PetalburgCity_Mart_TMs
    msgbox PetalburgCity_Text_ComeAgain, MSGBOX_DEFAULT
    release
    end

.align 2
PetalburgCity_Mart_TMs::
    .2byte ITEM_TM31     // TM31
    .2byte ITEM_TM32     // TM32
    .2byte ITEM_TM33     // TM33
    .2byte ITEM_TM34     // TM34
    .2byte ITEM_TM35     // TM35
    .2byte ITEM_TM36     // TM36
    .2byte ITEM_TM37     // TM37
    .2byte ITEM_TM38     // TM38
    .2byte ITEM_TM39     // TM39
    .2byte ITEM_TM40     // TM40
    .2byte ITEM_TM41     // TM41
    .2byte ITEM_TM42     // TM42
    .2byte ITEM_TM43     // TM43
    .2byte ITEM_TM44     // TM44
    .2byte ITEM_TM45     // TM45
    .2byte ITEM_TM46     // TM46
    .2byte ITEM_TM47     // TM47
    .2byte ITEM_TM48     // TM48
    .2byte ITEM_TM49     // TM49
    .2byte ITEM_TM50     // TM50
    .2byte ITEM_TM51     // TM51
    .2byte ITEM_TM52     // TM52
    .2byte ITEM_TM53     // TM53
    .2byte ITEM_TM54     // TM54
    .2byte ITEM_TM55     // TM55
    .2byte ITEM_TM56     // TM56
    .2byte ITEM_TM57     // TM57
    .2byte ITEM_TM58     // TM58
    .2byte ITEM_TM59     // TM59
    .2byte ITEM_TM60     // TM60
    .2byte ITEM_TM61     // TM61
    .2byte ITEM_TM62     // TM62
    .2byte ITEM_TM63     // TM63
    .2byte ITEM_TM64     // TM64
    .2byte ITEM_TM65     // TM65
    .2byte ITEM_NONE
    end
