poryRustboroCity_Mart_TM_Seller::
    lock
    faceplayer
    message RustboroCity_Text_TMsForSale
    waitmessage
    pokemart RustboroCity_Mart_TMs
    msgbox RustboroCity_Text_ComeAgain, MSGBOX_DEFAULT
    release
    end

.align 2
RustboroCity_Mart_TMs::
    .2byte ITEM_TM_BRUTAL_SWING    // TM105
    .2byte ITEM_TM_UTURN           // TM106
    .2byte ITEM_TM_THUNDER_FANG    // TM107
    .2byte ITEM_TM_ICE_FANG        // TM108
    .2byte ITEM_TM_FIRE_FANG       // TM109
    .2byte ITEM_TM_ROCK_SLIDE      // TM110
    .2byte ITEM_TM_BULLETPROOF     // TM111
    .2byte ITEM_TM_THUNDERBOLT     // TM112
    .2byte ITEM_TM_GYRO_BALL       // TM113
    .2byte ITEM_TM_SWORDS_DANCE    // TM114
    .2byte ITEM_TM_STEALTH_ROCK    // TM115
    .2byte ITEM_TM_EARTHQUAKE      // TM116
    .2byte ITEM_TM_PSYCHIC         // TM117
    .2byte ITEM_TM_ICE_BEAM        // TM118
    .2byte ITEM_TM_BLIZZARD        // TM119
    .2byte ITEM_TM_BULLETPUNCH     // TM120
    .2byte ITEM_TM_DRAGON_PULSE    // TM121
    .2byte ITEM_TM_DARK_PULSE      // TM122
    .2byte ITEM_TM_WILD_CHARGE     // TM123
    .2byte ITEM_TM_DREAM_EATER     // TM124
    .2byte ITEM_TM_SWIFT           // TM125
    .2byte ITEM_TM_THUNDER_WAVE    // TM126
    .2byte ITEM_TM_PAY_DAY         // TM127
    .2byte ITEM_TM_RECYCLE         // TM128
    .2byte ITEM_TM_GROWTH          // TM129
    .2byte ITEM_TM_WORK_UP         // TM130
    .2byte ITEM_TM_VOLT_SWITCH     // TM131
    .2byte ITEM_TM_SMART_STRIKE    // TM132
    .2byte ITEM_TM_SCALD           // TM133
    .2byte ITEM_TM_FOCUS_BLAST     // TM134
    .2byte ITEM_TM_DARK_PULSE      // TM135
    .2byte ITEM_TM_ENERGY_BALL     // TM136
    .2byte ITEM_TM_DRAIN_PUNCH     // TM137
    .2byte ITEM_TM_VENOSHOCK       // TM138
    .2byte ITEM_TM_X_SCISSOR       // TM139
    .2byte ITEM_TM_ACROBATICS      // TM140
    .2byte ITEM_TM_WILD_CHARGE     // TM141
    .2byte ITEM_TM_QUASH           // TM142
    .2byte ITEM_TM_KNOCK_OFF       // TM143
    .2byte ITEM_TM_BRUTAL_SWING    // TM144
    .2byte ITEM_TM_UTURN           // TM145
    .2byte ITEM_TM_THUNDER_FANG    // TM146
    .2byte ITEM_TM_ICE_FANG        // TM147
    .2byte ITEM_TM_FIRE_FANG       // TM148
    .2byte ITEM_TM_ROCK_SLIDE      // TM149
    .2byte ITEM_TM_BULLETPROOF     // TM150
    .2byte ITEM_TM_THUNDERBOLT     // TM151
    .2byte ITEM_TM_GYRO_BALL       // TM152
    .2byte ITEM_TM_SWORDS_DANCE    // TM153
    .2byte ITEM_TM_STEALTH_ROCK    // TM154
    .2byte ITEM_TM_EARTHQUAKE      // TM155
    .2byte ITEM_TM_PSYCHIC         // TM156
    .2byte ITEM_NONE
    end
