poryRustboroCity_Mart_TM_Seller::
    lock
    faceplayer
    message RustboroCity_Text_TMsForSale
    waitmessage
    pokemart RustboroCity_Mart_TMs
    msgbox RustboroCity_Text_ComeAgain, MSGBOX_DEFAULT
    release
    end

.align 2
RustboroCity_Mart_TMs::
    .2byte ITEM_TM66     // TM66
    .2byte ITEM_TM67     // TM67
    .2byte ITEM_TM68     // TM68
    .2byte ITEM_TM69     // TM69
    .2byte ITEM_TM70     // TM70
    .2byte ITEM_TM71     // TM71
    .2byte ITEM_TM72     // TM72
    .2byte ITEM_TM73     // TM73
    .2byte ITEM_TM74     // TM74
    .2byte ITEM_TM75     // TM75
    .2byte ITEM_TM76     // TM76
    .2byte ITEM_TM77     // TM77
    .2byte ITEM_TM78     // TM78
    .2byte ITEM_TM79     // TM79
    .2byte ITEM_TM80     // TM80
    .2byte ITEM_TM81     // TM81
    .2byte ITEM_TM82     // TM82
    .2byte ITEM_TM83     // TM83
    .2byte ITEM_TM84     // TM84
    .2byte ITEM_TM85     // TM85
    .2byte ITEM_TM86     // TM86
    .2byte ITEM_TM87     // TM87
    .2byte ITEM_TM88     // TM88
    .2byte ITEM_TM89     // TM89
    .2byte ITEM_TM90     // TM90
    .2byte ITEM_TM91     // TM91
    .2byte ITEM_TM92     // TM92
    .2byte ITEM_TM93     // TM93
    .2byte ITEM_TM94     // TM94
    .2byte ITEM_TM95     // TM95
    .2byte ITEM_TM96     // TM96
    .2byte ITEM_TM97     // TM97
    .2byte ITEM_TM98     // TM98
    .2byte ITEM_TM99     // TM99
    .2byte ITEM_TM100    // TM100
    .2byte ITEM_NONE
    end